AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating an ECR repository for the Contrast Security .NET Framework agent demo'

Resources:
  ContrastDemoRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: dotnet-framework-contrast-sample
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryURI:
    Description: 'URI of the created ECR repository'
    Value: !GetAtt ContrastDemoRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryURI"
