name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'docker/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'docker/**'
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    env:
      ECR_REPOSITORY: dotnet-framework-contrast-sample
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Debug AWS credentials
      shell: pwsh
      run: |
        if (-not [string]::IsNullOrEmpty("${{ secrets.AWS_ACCESS_KEY_ID }}")) {
          Write-Output "AWS_ACCESS_KEY_ID is set (not showing value for security)"
        } else {
          Write-Output "AWS_ACCESS_KEY_ID is not set"
        }
        
        if (-not [string]::IsNullOrEmpty("${{ secrets.AWS_SECRET_ACCESS_KEY }}")) {
          Write-Output "AWS_SECRET_ACCESS_KEY is set (not showing value for security)"
        } else {
          Write-Output "AWS_SECRET_ACCESS_KEY is not set"
        }

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src
        file: ./docker/Dockerfile
        platforms: windows/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest