name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'docker/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'docker/**'
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    env:
      ECR_REPOSITORY: dotnet-framework-contrast-sample
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and tag Docker image
      shell: pwsh
      run: |
        $registry = "${{ steps.login-ecr.outputs.registry }}"
        docker build -t $registry/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} -t $registry/${{ env.ECR_REPOSITORY }}:latest -f ./docker/Dockerfile ./src
    
    - name: Push Docker image
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: |
        $registry = "${{ steps.login-ecr.outputs.registry }}"
        docker push $registry/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        docker push $registry/${{ env.ECR_REPOSITORY }}:latest